/*
 * Copyright © 2017 Alain Kägi
 */

package ldbc.queries;

import com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcQuery8Result;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

import java.text.SimpleDateFormat;

import ldbc.utils.Explanation;

/**
 * The Query8 class implements an application that runs complex read
 * query 8 from the LDBC Social Network Benchmark (SNB) as a
 * microbenchmark.  As input, it expects a parameter substitution
 * parameter file as generated by the LDBC SNB data generator.
 */
public class Query8 implements ExecutableQuery {

    /* Static query parameters. */
    private static final String queryName = "Query8";
    private static final String queryParameterFilename = "query_8_param.txt";
    private static final String queryParameterFileLinePattern = "(\\d+)";
    private static final int queryLimit = 20;
    private static final String queryString =
        "   SELECT Person.id, Person.firstName, Person.lastName, " +
        "          Message.creationDate, Message.id, Message.content " +
        "     FROM Person, Message, CommentReplyOfMessage, " +
        "          MessageHasCreatorPerson as MessageHasCreatorPerson, " +
        "          MessageHasCreatorPerson as CommentHasCreatorPerson " +
        "    WHERE ? = MessageHasCreatorPerson.personId " +
        "      AND MessageHasCreatorPerson.messageId = CommentReplyOfMessage.messageId " +
        "      AND CommentReplyOfMessage.commentId = CommentHasCreatorPerson.messageId " +
        "      AND CommentHasCreatorPerson.personId = Person.id " +
        "      AND CommentReplyOfMessage.commentId = Message.id " +
        " ORDER BY Message.creationDate DESC, Message.id " +
        "    LIMIT ?";

    /** A minimal constructor. */
    private Query8() {}

    /**
     * Run LDBC SNB complex read query 8 as a microbenchmark.
     *
     * <p>A configuration file called <tt>params.ini</tt> specifies
     * the running parameters.
     *
     * @param args  Unused
     */
    public static void main(String[] args) {
        Microbenchmark.executeQueryWithParametersFromFile(new Query8(), queryName, queryParameterFilename, queryParameterFileLinePattern);
    }

    /**
     * Recent replies (eighth complex read query).
     * @param db        A database handle
     * @param personId  The person's unique identifier
     * @param limit     An upper bound on the number of results returned
     * @return The top 'limit' most recent comments that are replies to messages created by the given person
     * @throws SQLException if a database access error occurs
     */
    public static List<LdbcQuery8Result> query(Connection db, long personId, int limit) throws SQLException {
        List<LdbcQuery8Result> results = new ArrayList<>();

        PreparedStatement s = db.prepareStatement(queryString);
        s.setLong(1, personId);
        s.setInt(2, limit);
        ResultSet r = s.executeQuery();
        while (r.next()) {
            LdbcQuery8Result result = new LdbcQuery8Result(
                r.getLong("Person.id"),
                r.getString("Person.firstName"),
                r.getString("Person.lastName"),
                r.getLong("Message.creationDate"),
                r.getLong("Message.id"),
                r.getString("Message.content"));
            results.add(result);
        }

        return results;
    }

    /**
     * Explain query 8 with the given inputs.
     * @param db        A database handle
     * @param personId  The person's unique identifier
     * @param limit     An upper bound on the number of results returned
     * @return information about the query execution plan
     * @throws SQLException if a database access error occurs
     */
    private static ResultSet explain(Connection db, long personId, int limit) throws SQLException {
        PreparedStatement s = db.prepareStatement(Explanation.query + queryString);
        s.setLong(1, personId);
        s.setInt(2, limit);
        return s.executeQuery();
    }

    /**
     * Execute the query once for every query parameters.
     * @param db               A database handle
     * @param queryParameters  Stream of query input parameters
     * @param beVerbose        Print query outputs if true
     * @param printHeapUsage   Print heap usage if true
     * @throws SQLException if a database access error occurs
     */
    public void executeQuery(Connection db, QueryParameterFile queryParameters, boolean beVerbose, boolean printHeapUsage) throws SQLException {
        HeapUsage heapUsage = new HeapUsage();

        while (queryParameters.nextLine()) {
            long personId = queryParameters.getLong();

            if (printHeapUsage)
                heapUsage.print(System.out);

            List<LdbcQuery8Result> results = query(db, personId, queryLimit);

            if (beVerbose)
                print(personId, results);
        }
    }

    /**
     * Explain the query with the first set of query parameters.
     * @param db               A database handle
     * @param queryParameters  Stream of query input parameters
     * @throws SQLException if a database access error occurs
     */
    public void explainQuery(Connection db, QueryParameterFile queryParameters) throws SQLException {
        if (queryParameters.nextLine()) {
            long personId = queryParameters.getLong();

            ResultSet r = explain(db, personId, queryLimit);

            ldbc.utils.Explanation.print(System.out, r);
        }
    }

    /**
     * Pretty print the query 8 results.
     * @param personId  Query 8 parameter 1
     * @param results   Query 8 results
     */
    private static void print(long personId, List<LdbcQuery8Result> results) {
        System.out.println(personId);

        if (results.size() == 0) {
            System.out.println("  no matches");
            System.out.println("");
            return;
        }

        SimpleDateFormat dateTimeZFmt = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        dateTimeZFmt.setTimeZone(TimeZone.getTimeZone("UTC"));

        for (LdbcQuery8Result result : results) {
            System.out.println("  " + result.personId()
                               + ", " + result.personFirstName()
                               + " " + result.personLastName()
                               + ", " + dateTimeZFmt.format(new Date(result.commentCreationDate()))
                               + ", " + result.commentId()
                               + ", " + result.commentContent());
        }

        System.out.println("");
    }

}
